name: modular_di_dart
description: Demonstrates modular DI using ForceInject
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  force_inject:
    path: ../../packages/force_inject

dev_dependencies:
  test: ^1.25.0
