name: force_inject_flutter
version: 0.2.0
description: Flutter integration for ForceInject – scoped DI made clean.

homepage: https://github.com/diegomgarcia/force_inject
repository: https://github.com/diegomgarcia/force_inject
issue_tracker: https://github.com/diegomgarcia/force_inject/issues

environment:
  sdk: ^3.6.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  force_inject: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

resolution: workspace
