name: force_inject_provider
description: Provider integration for ForceInject — a lightweight dependency injection container for Dart and Flutter.
version: 0.1.0

homepage: https://github.com/diegomgarcia/force_inject
repository: https://github.com/diegomgarcia/force_inject
issue_tracker: https://github.com/diegomgarcia/force_inject/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  force_inject: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

resolution: workspace